#!/bin/bash
set -e
manager=$2
disker=$3
filetype=$1
filename=`flumotion-command -m $manager component -i $disker property get filename | cut -f5 -d"'" `
# make sure file is not empty
echo "filename $filename"
echo "args: $@"
while true; do
  if stat $filename | grep empty; then
    continue;
  else break;
  fi
done
if file $filename | grep $filetype
then exit 0;
else exit 1;
fi
