#!/bin/bash
set -e
manager=$1
component=$2
mood=$3
while true; do
  res=`flumotion-command -m $manager component -i $component mood`
  echo "$res, $mood"
  if echo $res | grep $mood; then
    exit 0
  fi
  sleep 1
done
